import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/header";

const helvetica = localFont({
  src: [
    {
      path: "./fonts/HelveticaNeueCyr/helveticaneuecyr_thin.otf",
      weight: "100",
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNeueCyr/helveticaneuecyr_ultralight.otf",
      weight: "200",
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNeueCyr/helveticaneuecyr_roman.otf", // Це твій основний текст
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNeueCyr/helveticaneuecyr_black.otf", // Для жирних заголовків
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-helvetica",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={helvetica.variable}>
        <Header />
        {children}
      </body>
    </html>
  );
}
